### ISSUE TITLE
Some Problem With The Notebook

### ISSUE THREAD

**Issue by KennethChiuT** [RafaelBehrens/ASO-python-keyword-optimisation#1]
When i run the notebook, there is something wrong. I am new about this, sorry to bother you.
![image](https://user-images.githubusercontent.com/25679217/48878662-620c6880-ee43-11e8-955c-c4531480a142.png)
![image](https://user-images.githubusercontent.com/25679217/48878679-6e90c100-ee43-11e8-93cc-024f769b8650.png)
![image](https://user-images.githubusercontent.com/25679217/48878686-75b7cf00-ee43-11e8-9eaf-258ba3445977.png)

**Comment by RafaelBehrens** [comment]
Hey Kenneth!
So sorry, I only just saw this, ‘pd is not defined’ suggests that you haven’t installed the python framework ‘Pandas’, see how I’m importing pandas as pd at the top of the notebook? Just do pip install pandas in the terminal to install it globally.
